spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
      name: microservicecloud-config-kevin-dev
---
spring:
  profiles: test  #测试环境
  application:
      name: microservicecloud-config-kevin-test
# 另存为 UTF-8 格式！！！